### ISSUE TITLE
Issue with babel package

### ISSUE THREAD

**Issue by sephi-dev** [ronanlevesque/FOX-Boilerplate-2#1]
Hi Ronan, I think Babel package changes its name to babel-core. Think to update to make it works ! Cheers !

**Comment by sephi-dev** [comment]
Another error with your framework is the live reload for HTML. It doesn't work anymore.
babel-core fix it for sass and javascript instead.

**Comment by ronanlevesque** [comment]
Thanks mate, fixed by https://github.com/ronanlevesque/FOX-Boilerplate-2/commit/e7fe1bc1141dac893dd22816b2be88813700f674
